package dev.thematrix.tvhk

object MovieList {
    const val FB_INDEX = 8
    const val FB_CATEGORY_INDEX = 1

    val CATEGORY = arrayOf(
        "新聞",
        "HK01",
        "體育",
        "FOX體育",
        "有線電視",
        "ViuTV",
        "RTHK",
        "UTV",
        "台灣",
        "UAE",
        "印尼",
        "廣東電視",
        "澳門TDM"
    )

    val TITLE = mutableListOf(
        "有線財經資訊台",
        "有線直播台",
        "有線新聞台",
        "now新聞台",
        "now直播台",
        "港台電視32",
        "SKIP",
        "HK01",
        "HK01",
        "HK01",
        "SKIP",
        "now630",
        "CCTV5",
        "CCTV5+",
        "廣東體育",
        "澳視體育",
        "博斯魅力",
        "皇馬台",
        "NBATV",
        "SKIP",
        "FS1",
        "FS2",
        "FS3",
        "FS4",
        "SKIP",
        "香港開電視",
        "有線綜合娛樂台",
        "SKIP",
        "ViuTV",
        "SKIP",
        "港台電視31",
        "SKIP",
        "C+",
        "賽馬頻道",
        "SKIP",
        "民視新聞",
        "三立新聞",
        "SKIP",
        "國家地理頻道",
        "國家地理野生頻道",
        "國家地理歷險頻道",
        "H2 HD",
        "RT Doc",
        "Star Movies",
        "Star World",
        "Tv5 Monde",
        "MBC2 Movie",
        "MBC Max",
        "MBC Action",
        "SKIP",
        "天映頻道",
        "Thrill",
        "NHK World",
        "Channel News Asia",
        "Aljazeera News",
        "Cinema World",
        "GemTV",
        "Hits",
        "SKIP",
        "廣東衛視",
        "珠江頻道",
        "公共頻道",
        "新聞頻道",
        "嘉佳卡通",
        "國際頻道",
        "TVS1經濟科教",
        "TVS2南方衛視",
        "TVS3廣東綜藝",
        "TVS4廣東影視",
        "TVS5廣東少兒",
        "房產頻道",
        "現代教育",
        "文化頻道",
        "SKIP",
        "澳視澳門",
        "澳門資訊",
        "澳門綜藝",
        "澳門-MACAU",
        "澳視葡文",
        "SKIP"
    )

    val DESCRIPTION = mutableListOf(
        "",
        "畫面比例可能不符合你的電視",
        "",
        "",
        "",
        "",
        "SKIP",
        "",
        "",
        "",
        "SKIP",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "SKIP",
        "",
        "",
        "",
        "",
        "SKIP",
        "",
        "",
        "SKIP",
        "",
        "SKIP",
        "",
        "SKIP",
        "",
        "",
        "SKIP",
        "",
        "",
        "SKIP",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "SKIP",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "SKIP",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "SKIP",
        "",
        "",
        "",
        "",
        "",
        "SKIP"
    )

    val CARD_IMAGE_URL = mutableListOf(
        R.drawable.cablefinance,
        R.drawable.cablelivenews,
        R.drawable.cablenews,
        R.drawable.nowtv332,
        R.drawable.nowtv331,
        R.drawable.rthktv32,
        0,
        R.drawable.fb_hk01wemedia,
        R.drawable.fb_hk01wemedia,
        R.drawable.fb_hk01wemedia,
        0,
        R.drawable.nowtv630,
        R.drawable.cctv5,
        R.drawable.cctv5plus,
        R.drawable.gdtv_sports,
        R.drawable.tdmsport,
        R.drawable.sportcast,
        R.drawable.rmtv,
        R.drawable.nbatv,
        0,
        R.drawable.foxsports,
        R.drawable.foxsports,
        R.drawable.foxsports,
        R.drawable.foxsports,
        0,
        R.drawable.opentv,
        R.drawable.cableentertainment,
        0,
        R.drawable.viutv,
        0,
        R.drawable.rthktv31,
        0,
        R.drawable.utv,
        R.drawable.utv,
        0,
        R.drawable.tw_ftvn,
        R.drawable.tw_setn,
        0,
        R.drawable.uae_natgeo,
        R.drawable.uae_natgeowild,
        R.drawable.uae_natgeopeople,
        R.drawable.uae_history2,
        R.drawable.uae_rtdoc,
        R.drawable.uae_starmovies,
        R.drawable.uae_starworld,
        R.drawable.uae_tv5monde,
        R.drawable.uae_mbc2,
        R.drawable.uae_mbcmax,
        R.drawable.uae_mbcaction,
        0,
        R.drawable.in_celestial,
        R.drawable.in_thrill,
        R.drawable.in_nhkworld,
        R.drawable.in_cna,
        R.drawable.in_aljazeera,
        R.drawable.in_cinemaworld,
        R.drawable.in_gem,
        R.drawable.in_hits,
        0,
        R.drawable.gdtv_star,
        R.drawable.gdtv_zj,
        R.drawable.gdtv_public,
        R.drawable.gdtv_news,
        R.drawable.gdtv_cartoon,
        R.drawable.gdtv_world,
        R.drawable.gdtv_tvs1,
        R.drawable.gdtv_tvs2,
        R.drawable.gdtv_tvs3,
        R.drawable.gdtv_tvs4,
        R.drawable.gdtv_tvs5,
        R.drawable.gdtv_house,
        R.drawable.gdtv_edu,
        R.drawable.gdtv_wh,
        0,
        R.drawable.tdmmacau,
        R.drawable.tdminfo,
        R.drawable.tdmhd,
        R.drawable.tdmsat,
        R.drawable.tdmportugal,
        0
    )

    val VIDEO_URL = mutableListOf(
        "",
        "",
        "",
        "",
        "",
        "https://www.rthk.hk/feeds/dtt/rthktv32_https.m3u8",
        "SKIP",
        "http://live.cdn.hk01.com/origin/smil:01news.smil/playlist.m3u8",
        "http://live2.cdn.hk01.com/origin/smil:Sudden01.smil/playlist.m3u8",
        "http://live.cdn.hk01.com/origin/smil:EventBox001.smil/playlist.m3u8",
        "SKIP",
        "",
        "http://111.40.205.87/PLTV/88888888/224/3221225591/index.m3u8",
        "http://111.40.205.87/PLTV/88888888/224/3221225689/index.m3u8",
        "",
        "http://live1.tdm.com.mo:1935/ch4/sport_ch4.live/playlist.m3u8#http://live2.tdm.com.mo:1935/ch4/sport_ch4.live/playlist.m3u8#http://live3.tdm.com.mo:1935/ch4/sport_ch4.live/playlist.m3u8#http://live4.tdm.com.mo:1935/ch4/sport_ch4.live/playlist.m3u8",
        "http://ms003.happytv.com.tw/live/OcScNdWHvBx5P4w3/index.m3u8",
        "http://rmtv24hweblive-lh.akamaihd.net/i/rmtv24hwebes_1@300661/master.m3u8#http://rmtv24hweblive-lh.akamaihd.net/i/rmtv24hweben_1@300662/master.m3u8",
        "",
        "SKIP",
        "http://foxsportstw-lh.akamaihd.net/i/live01_0@38035/master.m3u8",
        "http://foxsportstw-lh.akamaihd.net/i/live01_0@38037/master.m3u8",
        "http://foxsportstw-lh.akamaihd.net/i/live01_0@455127/master.m3u8",
        "http://foxsportstw-lh.akamaihd.net/i/live01_0@570534/master.m3u8",
        "SKIP",
        "http://media.fantv.hk/m3u8/archive/channel2.m3u8",
        "",
        "SKIP",
        "",
        "SKIP",
        "https://www.rthk.hk/feeds/dtt/rthktv31_https.m3u8",
        "SKIP",
        "",
        "",
        "SKIP",
        "http://210.61.56.23/hls/ftvtv/index.m3u8#http://6.mms.vlog.xuite.net/hls/ftvtv/index.m3u8#http://1.mms.vlog.xuite.net/hls/ftvtv/index.m3u8",
        "http://60.199.188.65/HLS/WG_ETTV-N/index.m3u8",
        "SKIP",
        "http://livecdnh1.tvanywhere.ae:80/hls/nat_geo/index.m3u8",
        "http://livecdnh1.tvanywhere.ae:80/hls/nat_geo_wild/index.m3u8",
        "http://livecdnh1.tvanywhere.ae:80/hls/nat_geo_people/index.m3u8",
        "http://livecdnh1.tvanywhere.ae:80/hls/h2/index.m3u8",
        "http://livecdnh1.tvanywhere.ae:80/hls/rt_doc/index.m3u8",
        "http://livecdnh1.tvanywhere.ae:80/hls/star_movies/index.m3u8",
        "http://livecdnh1.tvanywhere.ae:80/hls/star_world/index.m3u8",
        "http://livecdnh1.tvanywhere.ae:80/hls/tv5/index.m3u8",
        "http://livecdnh3.tvanywhere.ae/hls/mbc2/index.m3u8",
        "http://livecdnh3.tvanywhere.ae/hls/mbcmax/index.m3u8",
        "http://livecdnh3.tvanywhere.ae/hls/mbcaction/index.m3u8",
        "SKIP",
        "http://45.126.83.51/qwr9ew/s/s33/index.m3u8#http://210.210.155.35/qwr9ew/s/s33/index.m3u8",
        "http://45.126.83.51/qwr9ew/s/s34/index.m3u8#http://210.210.155.35/qwr9ew/s/s34/index.m3u8",
        "http://45.126.83.51/uq2663/h/h23/index.m3u8#http://210.210.155.35/uq2663/h/h23/index.m3u8",
        "http://45.126.83.51/uq2663/h/h29/index.m3u8#http://210.210.155.35/uq2663/h/h29/index.m3u8",
        "http://45.126.83.51/qwr9ew/s/s17/index.m3u8#http://210.210.155.35/qwr9ew/s/s17/index.m3u8",
        "http://45.126.83.51/uq2663/h/h04/index2.m3u8#http://210.210.155.35/uq2663/h/h04/index2.m3u8",
        "http://45.126.83.51/uq2663/h/h19/index.m3u8#http://210.210.155.35/uq2663/h/h19/index.m3u8",
        "http://45.126.83.51/uq2663/h/h37/index.m3u8#http://210.210.155.35/uq2663/h/h37/index.m3u8",
        "SKIP",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "SKIP",
        "http://live1.tdm.com.mo:1935/ch1/ch1.live/playlist.m3u8#http://live2.tdm.com.mo:1935/ch1/ch1.live/playlist.m3u8#http://live3.tdm.com.mo:1935/ch1/ch1.live/playlist.m3u8#http://live4.tdm.com.mo:1935/ch1/ch1.live/playlist.m3u8",
        "http://live1.tdm.com.mo:1935/ch5/info_ch5.live/playlist.m3u8#http://live2.tdm.com.mo:1935/ch5/info_ch5.live/playlist.m3u8#http://live3.tdm.com.mo:1935/ch5/info_ch5.live/playlist.m3u8#http://live4.tdm.com.mo:1935/ch5/info_ch5.live/playlist.m3u8",
        "http://live1.tdm.com.mo:1935/ch6/hd_ch6.live/playlist.m3u8#http://live2.tdm.com.mo:1935/ch6/hd_ch6.live/playlist.m3u8#http://live3.tdm.com.mo:1935/ch6/hd_ch6.live/playlist.m3u8#http://live4.tdm.com.mo:1935/ch6/hd_ch6.live/playlist.m3u8",
        "http://live1.tdm.com.mo:1935/ch3/ch3.live/playlist.m3u8#http://live2.tdm.com.mo:1935/ch3/ch3.live/playlist.m3u8#http://live3.tdm.com.mo:1935/ch3/ch3.live/playlist.m3u8#http://live4.tdm.com.mo:1935/ch3/ch3.live/playlist.m3u8",
        "http://live1.tdm.com.mo:1935/ch2/ch2.live/playlist.m3u8#http://live2.tdm.com.mo:1935/ch2/ch2.live/playlist.m3u8#http://live3.tdm.com.mo:1935/ch2/ch2.live/playlist.m3u8#http://live4.tdm.com.mo:1935/ch2/ch2.live/playlist.m3u8",
        "SKIP"
    )

    val FUNC = mutableListOf(
        "wowgua_ch108",
        "cabletv110",
        "wowgua_ch109",
        "nowtv332",
        "nowtv331",
        "rthk32",
        "hkatv",
        "SKIP",
        "",
        "",
        "SKIP",
        "nowtv630",
        "",
        "",
        "gdtv_27",
        "",
        "",
        "",
        "wowgua_nbatv",
        "SKIP",
        "fox",
        "fox",
        "fox",
        "fox",
        "SKIP",
        "fantv",
        "wowgua_ch301",
        "SKIP",
        "viutv99",
        "SKIP",
        "rthk31",
        "SKIP",
        "wowgua_utv_c_plus",
        "wowgua_utv_racing",
        "SKIP",
        "tw",
        "",
        "SKIP",
        "uae",
        "uae",
        "uae",
        "uae",
        "uae",
        "uae",
        "uae",
        "uae",
        "uae",
        "uae",
        "uae",
        "SKIP",
        "in",
        "in",
        "in",
        "in",
        "in",
        "in",
        "in",
        "in",
        "SKIP",
        "gdtv_25",
        "gdtv_26",
        "gdtv_31",
        "gdtv_28",
        "gdtv_29",
        "gdtv_30",
        "gdtv_93",
        "gdtv_7",
        "gdtv_166",
        "gdtv_37",
        "gdtv_38",
        "gdtv_33",
        "gdtv_169",
        "gdtv_172",
        "SKIP",
        "",
        "",
        "",
        "",
        "",
        "SKIP"
    )

    val list: MutableList<Movie> by lazy {
        setupMovies()
    }

    fun updateList() {
        count = FB_INDEX

        val newMovieCount = TITLE.count() - list.count()

        //Fix index
        list.forEachIndexed { index, movie ->
            if (index >= FB_INDEX)
            {
                movie.id += newMovieCount
            }
        }

        //ADD new
        for (i in 0 until newMovieCount)
        {
            val movie = buildMovieInfo(
                TITLE[count],
                DESCRIPTION[count],
                CARD_IMAGE_URL[count],
                VIDEO_URL[count],
                FUNC[count]
            )
            list.add(count - 1, movie)
        }
    }

    private var count: Int = 0

    private fun setupMovies(): MutableList<Movie> {


        val list = TITLE.indices.map {
            buildMovieInfo(
                TITLE[it],
                DESCRIPTION[it],
                CARD_IMAGE_URL[it],
                VIDEO_URL[it],
                FUNC[it]
            )
        }

        return list.toMutableList()
    }

    private fun buildMovieInfo(
        title: String,
        description: String,
        cardImageUrl: Int,
        videoUrl: String,
        func: String
    ): Movie {
        val movie = Movie()
        movie.id = count++
        movie.title = title
        movie.description = description
        movie.cardImageUrl = cardImageUrl
        movie.videoUrl = videoUrl
        movie.func = func
        movie.exo = if (android.os.Build.VERSION.SDK_INT < 21)
            func in arrayOf("viutv99", "nowtv332", "nowtv331", "nowtv630", "fantv", "rthk31", "rthk32", "fox", "fb", "hkatv", "wowgua_nbatv", "wowgua_utv_c_plus", "wowgua_utv_racing", "wowgua_ch108", "wowgua_ch109", "wowgua_ch301", "in", "uae", "tw")
        else
            true


        return movie
    }
}
